-- create.sql -- 

-- Item Table --
CREATE TABLE Item (
ItemID INTEGER NOT NULL,
Name VARCHAR(200) NOT NULL,
Description VARCHAR(4000),
Started TIMESTAMP NOT NULL,
Ends TIMESTAMP NOT NULL,
Currently DECIMAL(8,2) NOT NULL,
Buy_Price DECIMAL(8,2) NOT NULL,
First_Bid DECIMAL(8,2) NOT NULL,
Number_of_Bids INTEGER,
Seller VARCHAR(50),
PRIMARY KEY (ItemID),
FOREIGN KEY (Seller) REFERENCES User(UserID)
);

-- Category Table --
CREATE TABLE Category (
CategoryID INTEGER NOT NULL PRIMARY KEY,
Category VARCHAR(50) NOT NULL
);

-- Item_Category Table --
CREATE TABLE Item_Category (
ItemID INTEGER NOT NULL,
CategoryID INTEGER NOT NULL,
PRIMARY KEY (ItemID, CategoryID),
FOREIGN KEY (ItemID) REFERENCES Item(ItemID),
FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
);

-- Bid Table --
CREATE TABLE Bid (
UserID VARCHAR(50) NOT NULL,
Time TIMESTAMP NOT NULL,
ItemID INTEGER NOT NULL,
Amount DECIMAL(8,2) NOT NULL,
PRIMARY KEY (UserID, Time),
FOREIGN KEY (ItemID) REFERENCES Item(ItemID),
FOREIGN KEY (UserID) REFERENCES User(UserID)
);

-- User Table -- 
CREATE TABLE User (
UserID VARCHAR(50) NOT NULL,
Rating INTEGER NOT NULL,
Location VARCHAR(50),
Country VARCHAR(30),
PRIMARY KEY (UserID)
);
