-- dropSQLIndex.sql --

USE CS144;

ALTER IGNORE TABLE Item DROP INDEX SellerIndex;
ALTER IGNORE TABLE Item DROP INDEX BuyPriceIndex;
ALTER IGNORE TABLE Item DROP INDEX EndTimeIndex;
ALTER IGNORE TABLE Bid DROP INDEX BidderIndex;
